// create web server
var express = require('express');
var app = express();
var bodyParser = require('body-parser');
var router = express.Router();
var fs = require('fs');
var path = require('path');
var url = require('url');
var mysql = require('mysql');
var dbConfig = require('../config/dbconfig');
var pool = mysql.createPool(dbConfig.mysql);
var moment = require('moment');